eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  main.banner_mode: 'off'
  output.ansi.enabled: always
  lifecycle.timeout-per-shutdown-phase: "20s"
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: update
    show-sql: false
    open-in-view: true
    
springdoc:
  show-actuator: true #Shows actuator endpoints in swagger ui

server.shutdown: graceful

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: [ "health", "info", "prometheus", "openapi", "swagger-ui" ]
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
